# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78db8e13b3b818f6e5e317dcda4e5f7592069773a405d52c619b4e3a57e8e52f406c6439e44dcd4fc2be6557e14606593e6e827964a0ac7967ab85002442c975

test:
  secret_key_base: ec2dfc53a305f6d7473a233aeec03ade925a080667b565811576ba5332428afba459a9808706e0f2d272eaae51ed3d9c994274c3b5c4d3ea421a5afedce3be75

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
